default_language_version:
  python: python3

exclude: |
  (?x)^(
    CODE_OF_CONDUCT.md |
    extensions/2.0/OMI_seat/examples/simple_chair_what.gltf
  )

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]

  - repo: local
    hooks:
      - id: file-format
        name: file-format
        language: python
        entry: python .github/workflows/file_format.py
        types_or: [text]
